### ISSUE TITLE
How to add your own themes

### ISSUE THREAD

**Issue by DawnImpulse** [williambelle/github-contribution-color-graph#17]
Hello,
I am trying to edit the **src/js/contentscript.js** file to add my own themes but unable to do so. Kindly tell me how can I create custom themes for my own usage.

**Comment by williambelle** [comment]
Hello,

After editing the file `src/js/contentscript.js`, you also need to add your theme in the `src/options.html`.

Example: https://github.com/williambelle/github-contribution-color-graph/pull/9/commits/db921729b74686adef914d4fbfbe3dfd9f636a6f

**Comment by DawnImpulse** [comment]
I did add colors right way in `src/js/contentscript.js` file but didn't saw the options in html file. Thanks a lot :)
