### ISSUE TITLE
Random Question

### ISSUE THREAD

**Issue by MichaelNeas** [williambelle/github-contribution-color-graph#5]
Thanks for the extension, works great for me! 

Super random question, have you ever come across why github chose to go with the default shades of green with no ability to customize?  

I remember when they changed the color scheme for Halloween and I've seen different blue and purple themes in different gitlabs, but this extension was the most customization I've been able to do from a user standpoint aside from modifying the rectangle fill temporarily.

**Comment by zfk513** [comment]
emm i am sick of the green , i like blue more
i think the change it is cuz lack of strong competition

**Comment by MoonAntonio** [comment]
I agree with @zfk513
